name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  matcher: ^0.12.13
  get: 4.6.5
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.14
  image_picker: ^0.8.6+4
  convex_bottom_bar: 3.2.0
  intl: 0.18.0
  geolocator: 9.0.2
  geocoding: 2.1.0
  syncfusion_flutter_datepicker: 22.1.37
  flutter: 
    sdk: flutter
  # flutter_launcher_icons: ^0.13.1
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

